she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('', views.AuthorView.as_view(), name='index'),
# Configure a URL for a single story view
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
# Configure a URL for the form to create story
    path('add-story/', views.AddStoryView.as_view(), name='newStory')

]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Added the URL for the App=news
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    # Added the URL for the App=users
    path('users/', include('users.urls')),
    # Added the URL for the App=users' Login page
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
# Added a URL to the form to create new account page
    path('create-account/', views.CreateAccountView.as_view(), name='createAccount'),   
# Added a UTL to the user profile page  
    path('<int:pk>/', views.UserView.as_view(), name='userProfile')
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.URLField(blank=False)
    # image_url = models.CharField(max_length=200, default="Enter a URL")

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'content','image_url']
        # Configure a date picker widget
        widgets = {'pub_date': forms.DateInput(format=('%m/%d/%Y'),attrs={'class':'form-control','placeholder':'Select a date','type':'date'}),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

# To create form for user login and updating
class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username','email']

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username','email']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        story_order = NewsStory.objects.all().order_by('-pub_date')
        context['latest_stories'] = story_order[:4]
        context['all_stories'] = story_order
        return context

# Added a view for a single story
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

# Added a view to use the form configured in forms.py
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    #Added to automatically take the logged in user's username as author
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class AuthorView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author_order = NewsStory.objects.all().order_by('-author')
        context['latest_stories'] = author_order[:4]
        context['all_stories'] = author_order
        return context

she_codes_news/users/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm

# Added a view for creating a new account
class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url= reverse_lazy('login')
    template_name= 'users/createAccount.html'

# Added a view for user profile
class UserView(generic.DetailView):
    model = CustomUser
    template_name = 'users/userProfile.html'
    context_object_name = 'user'

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

<form class="add-story" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="button" type="submit" value="Submit">

</form>

{% endblock %}

she_codes_news/news/templates/news/index.html
 <!-- news/templates/news/index.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

    <!-- <a href="{% url 'news:newStory' %}">Write New Story</a> -->
    
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}                
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <h2>All Stories</h2>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>


{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src="{{ story.image_url }}">
        {{ story.content|linebreaks }}
    </div>
</div>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <!-- To link from a story card to the story page -->
    <a href="{% url 'news:story' story.id %}">

    <!-- {% if position < 5 %} -->
        <img src="{{ story.image_url }}">
    <!-- {% else %}
        <img src="https://picsum.photos/600">
    {% endif %} -->
        
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
<!-- templates/base.html -->
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Marivic Mirhan">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{%static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}  
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock %}

        <footer>
            She Codes News
        </footer>

    </body>


</html>

she_codes_news/templates/nav.html
<nav class = "a-nav">

    <a id="a-nav" href="{% url 'news:index' %}">Home</a>                            <!--Added a link from template header to Home page-->
    
    {% if request.user.is_authenticated %}                                          <!--The nav links only shows when a user is logged in-->
        <a id="a-nav" href="#">Welcome, {{user.username}}</a>                       <!--Shows user's username-->
        <a id="a-nav" href="{% url 'news:newStory' %}">Write New Story</a>          <!--Added a link from template header to the form to add story -->
        <a id="a-nav" href="{% url 'logout' %}">Logout</a>                          <!--Shows "Logout"-->

    {% else %}                                                                      <!--The nav links only shows when NO user is logged in-->
        <a id="a-nav" href="{% url 'login'%}">Login</a>                             <!--Shows "Login"-->
        <a id="a-nav" href="{% url 'users:createAccount' %}">Create New Account</a> <!--Shows "Create New Account"-->

    {% endif %}
    
</nav>

<!-- superceded code -->
    <!-- <a id="a-nav" href="{% url 'users:createAccount' %}">Create New Account</a> -->
    <!-- <a id="a-nav" href="{% url 'news:newStory' %}">Write New Story</a> -->

she_codes_news/users/templates/users/changeAccount.html
{% extends 'base.html' %}

{% block content %}

<h2>Modify Existing Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button-style" type="submit">Submit</button>
</form>

{% endblock %}

she_codes_news/users/templates/users/createAccount.html
<!-- Created a form for creating a new account using base html as template-->

{% extends 'base.html' %}

{% block content %}

<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button-style" type="submit">Create Account</button>
</form>

{% endblock %}

she_codes_news/users/templates/users/userProfile.html
{% extends 'base.html' %}

{% block content %}

<h2>User Profile</h2>

<div>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p> 

</div>



{% endblock %}